# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Sleep for a random time (up to 15 minutes)
      shell: bash
      run: |
        RANDOM_NUMBER=$(( RANDOM % 900 ))  # Random number between 0 and 899 seconds
        echo "Sleeping for $RANDOM_NUMBER seconds"
        sleep $RANDOM_NUMBER
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v